### ISSUE TITLE
Include Code Of Conduct

### ISSUE THREAD

**Issue by xmnlab** [pyOpenSci/pyos-package-template#21]
Currently there is no much information about the Code of Conduct into the template: https://github.com/pyOpenSci/cookiecutter-pyopensci/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/CONTRIBUTING.rst#code-of-conduct

maybe would be good to add an option called "code_of_conduct" (or similar) with initial options that it could be "None" (maybe not), "NumFOCUS" and ["Contributor Covenant CoC V2"](https://www.contributor-covenant.org/version/2/0/code_of_conduct/code_of_conduct.txt).

and the content could be inside the current `CONTRIBUTING.rst#code-of-conduct` or add it to a `CODE_OF_CONDUCT` file

**Comment by lwasser** [comment]
@Midnighter i'm thinking that we should place those core files like COC and such in the main dir rather than the .github dir. I think this because we will have a strong usecase for scientists who aren't quite yet on GitHub or using .git but who may want to create a package. i'd like for them to be able to use our template too. 

we could add documentation around putting those files in the .github directory but i'd prefer to surface them and make them all default for the package regardless of whether someone selects GitHub or not. 

Does that seem reasonable to you?

**Comment by Midnighter** [comment]
Sounds good to me. It will require a few changes to the contributing guide, as that is sometimes GitHub-specific at the moment.

**Comment by Midnighter** [comment]
I just checked the [GitHub docs](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project#adding-a-code-of-conduct-manually) and they recognize three locations for the CoC guide. In the:

1. project root
2. `docs/`
3. `.github/`

The `docs/` is also a fairly natural location to me, but perhaps comes with a [caveat](https://github.com/pyOpenSci/pyos-package-template/issues/34#issuecomment-2434882639).
